In [1]:
import numpy as np
import scipy #only sparse matrices allowed
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import SGDClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from lightgbm import LGBMClassifier
from xgboost.sklearn import XGBClassifier

In [4]:
#We need to increase the categorization accuracy.

In [5]:
df_train = pd.read_csv(r"./ift3395-6390-weatherevents/train.csv")

In [6]:
submit_df = pd.read_csv(r"./ift3395-6390-weatherevents/test.csv")

In [7]:
df_train.head()

S.No        lat       lon        TMQ      U850      V850      UBOT  \
0     0 -24.758801  242.1875  16.019615 -4.391696  4.777769 -6.388222   
1     1  23.820078  277.8125  47.802036  8.623652  9.308566  4.596105   
2     2  23.820078  276.8750  11.556691 -2.483993 -6.009627 -3.503036   
3     3  13.494133  253.1250  53.186630  0.150933 -1.319407  3.757741   
4     4 -24.524120  241.2500  23.353998 -7.467506 -5.113565 -9.545109   

       VBOT    QREFHT           PS  ...        T200        T500         PRECT  \
0  7.725320  0.010277  102326.2344  ...  221.594223  261.823212  6.660000e-09   
1  9.938286  0.018531  100803.1094  ...  220.343719  269.106720  3.670000e-16   
2 -5.921963  0.007468  101885.3906  ...  215.933487  259.610718  0.000000e+00   
3 -2.172120  0.018809  100824.6328  ...  218.457672  267.374329  9.800000e-08   
4 -4.691221  0.011672  102553.8984  ...  214.316605  263.575409  6.410000e-09   

           TS      TREFHT       Z1000         Z200       ZBOT      time  \
0  295.622253  293.301514  197.698624  12234.78809  64.372635  20030804   
1  302.496826  302.654083   71.571518  12463.97266  66.834389  20071006   
2  299.854919  293.339996  160.414246  12099.36133  64.209663  20020331   
3  301.606934  299.973450   72.840614  12379.26855  66.243294  20000906   
4  295.819488  295.101257  218.449570  12261.22656  64.876427  20000906   

   LABELS  
0       0  
1       1  
2       0  
3       0  
4       0  

[5 rows x 21 columns]

In [8]:
def df_year_handler(df_train):
    #df_train is the train df loaded from our csv file
    #labels are not dealt with here, so keep them in a separate column before calling this
    #df_train2 = df_train.drop(columns=["S.No"])
    df_train2 = df_train
    #df_train2 = df_train
    #https://stackoverflow.com/questions/22005911/convert-columns-to-string-in-pandas
    #converting to string for the split
    df_train2["time"] = df_train2["time"].astype(str)
    #expand will return multiple columns with the split strings
    split_columns = df_train2["time"].str.split("",expand=True)
    year = split_columns[1] + split_columns[2] + split_columns[3] +split_columns[4]
    month = split_columns[5] + split_columns[6]
    date = split_columns[7] + split_columns[8]
    
    #converting series to df and renaming the column so we dont end up with a bunch of columns named 0
    #https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rename.html
    year = pd.DataFrame(year)
    month = pd.DataFrame(month)
    date = pd.DataFrame(date)

    year = year.rename(columns={0: "year"})
    month = month.rename(columns={0: "month"})
    date = date.rename(columns={0: "date"})

    #we need to convert the strings back to integers
    #https://datatofish.com/string-to-integer-dataframe/
    year['year'] = year['year'].astype(int)
    month['month'] = month['month'].astype(int)
    date['date'] = date['date'].astype(int)
    
    #adding these back to the original df
    df = pd.concat([df_train2, year, month, date], axis = 1)
    df = df.drop(columns=["time"])
    #df.head()
    
    return df

### I hear there are duplicates in the data

### There are samples which have the same feature values but different target values

### let's try to handle these

In [9]:
df_train

S.No        lat       lon        TMQ      U850      V850      UBOT  \
0          0 -24.758801  242.1875  16.019615 -4.391696  4.777769 -6.388222   
1          1  23.820078  277.8125  47.802036  8.623652  9.308566  4.596105   
2          2  23.820078  276.8750  11.556691 -2.483993 -6.009627 -3.503036   
3          3  13.494133  253.1250  53.186630  0.150933 -1.319407  3.757741   
4          4 -24.524120  241.2500  23.353998 -7.467506 -5.113565 -9.545109   
...      ...        ...       ...        ...       ...       ...       ...   
47755  47755 -30.625815  353.4375  14.680613  3.153518  4.250256 -0.406992   
47756  47756 -24.993481  242.1875  29.540585  9.181329 -0.369805  7.125068   
47757  47757 -30.625815  353.4375  20.991110  7.709649 -6.284292  3.702500   
47758  47758  23.585398  276.5625  45.689816 -3.018448  0.280351 -6.938124   
47759  47759  24.054759  276.8750  49.550251 -2.582931 -0.844238 -6.318487   

           VBOT    QREFHT           PS  ...        T200        T500  \
0      7.725320  0.010277  102326.2344  ...  221.594223  261.823212   
1      9.938286  0.018531  100803.1094  ...  220.343719  269.106720   
2     -5.921963  0.007468  101885.3906  ...  215.933487  259.610718   
3     -2.172120  0.018809  100824.6328  ...  218.457672  267.374329   
4     -4.691221  0.011672  102553.8984  ...  214.316605  263.575409   
...         ...       ...          ...  ...         ...         ...   
47755  3.480553  0.008333  102109.4844  ...  213.804184  259.846222   
47756 -5.466469  0.013645  101734.2813  ...  213.867416  263.996307   
47757 -7.359541  0.010529  101800.8516  ...  216.394852  264.192566   
47758  0.681055  0.020653  101641.2266  ...  217.026199  265.778900   
47759 -1.986166  0.017553  101374.0859  ...  217.422790  265.335571   

              PRECT          TS      TREFHT       Z1000         Z200  \
0      6.660000e-09  295.622253  293.301514  197.698624  12234.78809   
1      3.670000e-16  302.496826  302.654083   71.571518  12463.97266   
2      0.000000e+00  299.854919  293.339996  160.414246  12099.36133   
3      9.800000e-08  301.606934  299.973450   72.840614  12379.26855   
4      6.410000e-09  295.819488  295.101257  218.449570  12261.22656   
...             ...         ...         ...         ...          ...   
47755  2.470000e-09  291.791870  290.141663  177.677322  12058.16016   
47756  2.620000e-09  296.322327  296.220642  150.108871  12272.25781   
47757  4.240000e-09  290.757996  290.736847  152.666443  12232.26953   
47758  8.620000e-08  302.751862  301.542786  145.255554  12404.29297   
47759  2.270000e-08  301.325226  300.146851  121.040375  12352.48535   

            ZBOT      time  LABELS  
0      64.372635  20030804       0  
1      66.834389  20071006       1  
2      64.209663  20020331       0  
3      66.243294  20000906       0  
4      64.876427  20000906       0  
...          ...       ...     ...  
47755  63.678669  20001106       2  
47756  65.238327  20010712       2  
47757  63.929737  20011029       0  
47758  66.656548  20020712       0  
47759  66.221062  20081012       0  

[47760 rows x 21 columns]

In [10]:
df_train = df_year_handler(df_train)

In [11]:
labels = df_train[["LABELS"]]

In [12]:
df_train = df_train.drop(columns=["S.No","LABELS"])

In [13]:
df_train = pd.concat([df_train, labels],axis=1)

In [14]:
df_train

lat       lon        TMQ      U850      V850      UBOT      VBOT  \
0     -24.758801  242.1875  16.019615 -4.391696  4.777769 -6.388222  7.725320   
1      23.820078  277.8125  47.802036  8.623652  9.308566  4.596105  9.938286   
2      23.820078  276.8750  11.556691 -2.483993 -6.009627 -3.503036 -5.921963   
3      13.494133  253.1250  53.186630  0.150933 -1.319407  3.757741 -2.172120   
4     -24.524120  241.2500  23.353998 -7.467506 -5.113565 -9.545109 -4.691221   
...          ...       ...        ...       ...       ...       ...       ...   
47755 -30.625815  353.4375  14.680613  3.153518  4.250256 -0.406992  3.480553   
47756 -24.993481  242.1875  29.540585  9.181329 -0.369805  7.125068 -5.466469   
47757 -30.625815  353.4375  20.991110  7.709649 -6.284292  3.702500 -7.359541   
47758  23.585398  276.5625  45.689816 -3.018448  0.280351 -6.938124  0.681055   
47759  24.054759  276.8750  49.550251 -2.582931 -0.844238 -6.318487 -1.986166   

         QREFHT           PS          PSL  ...         PRECT          TS  \
0      0.010277  102326.2344  102326.2344  ...  6.660000e-09  295.622253   
1      0.018531  100803.1094  100803.1094  ...  3.670000e-16  302.496826   
2      0.007468  101885.3906  101885.3906  ...  0.000000e+00  299.854919   
3      0.018809  100824.6328  100824.6328  ...  9.800000e-08  301.606934   
4      0.011672  102553.8984  102553.8984  ...  6.410000e-09  295.819488   
...         ...          ...          ...  ...           ...         ...   
47755  0.008333  102109.4844  102109.4844  ...  2.470000e-09  291.791870   
47756  0.013645  101734.2813  101734.2813  ...  2.620000e-09  296.322327   
47757  0.010529  101800.8516  101800.8516  ...  4.240000e-09  290.757996   
47758  0.020653  101641.2266  101641.2266  ...  8.620000e-08  302.751862   
47759  0.017553  101374.0859  101374.0859  ...  2.270000e-08  301.325226   

           TREFHT       Z1000         Z200       ZBOT  year  month  date  \
0      293.301514  197.698624  12234.78809  64.372635  2003      8     4   
1      302.654083   71.571518  12463.97266  66.834389  2007     10     6   
2      293.339996  160.414246  12099.36133  64.209663  2002      3    31   
3      299.973450   72.840614  12379.26855  66.243294  2000      9     6   
4      295.101257  218.449570  12261.22656  64.876427  2000      9     6   
...           ...         ...          ...        ...   ...    ...   ...   
47755  290.141663  177.677322  12058.16016  63.678669  2000     11     6   
47756  296.220642  150.108871  12272.25781  65.238327  2001      7    12   
47757  290.736847  152.666443  12232.26953  63.929737  2001     10    29   
47758  301.542786  145.255554  12404.29297  66.656548  2002      7    12   
47759  300.146851  121.040375  12352.48535  66.221062  2008     10    12   

       LABELS  
0           0  
1           1  
2           0  
3           0  
4           0  
...       ...  
47755       2  
47756       2  
47757       0  
47758       0  
47759       0  

[47760 rows x 22 columns]

In [15]:
#Dropping raw duplicates with labels
df_temp1 = df_train.drop_duplicates()

In [16]:
df_temp1

lat       lon        TMQ       U850      V850      UBOT  \
0     -24.758801  242.1875  16.019615  -4.391696  4.777769 -6.388222   
1      23.820078  277.8125  47.802036   8.623652  9.308566  4.596105   
2      23.820078  276.8750  11.556691  -2.483993 -6.009627 -3.503036   
3      13.494133  253.1250  53.186630   0.150933 -1.319407  3.757741   
4     -24.524120  241.2500  23.353998  -7.467506 -5.113565 -9.545109   
...          ...       ...        ...        ...       ...       ...   
47743  23.585398  276.5625  41.815079  -5.981042  7.609122 -8.963073   
47744 -24.993481  242.5000  23.160349  -6.694213  1.401017 -8.668851   
47750  13.494133  253.7500  44.489532  -2.837747 -1.062834 -3.629961   
47754  13.024772  253.4375  53.848255  10.059551 -0.746791  9.813080   
47759  24.054759  276.8750  49.550251  -2.582931 -0.844238 -6.318487   

           VBOT    QREFHT           PS          PSL  ...         PRECT  \
0      7.725320  0.010277  102326.2344  102326.2344  ...  6.660000e-09   
1      9.938286  0.018531  100803.1094  100803.1094  ...  3.670000e-16   
2     -5.921963  0.007468  101885.3906  101885.3906  ...  0.000000e+00   
3     -2.172120  0.018809  100824.6328  100824.6328  ...  9.800000e-08   
4     -4.691221  0.011672  102553.8984  102553.8984  ...  6.410000e-09   
...         ...       ...          ...          ...  ...           ...   
47743  2.837600  0.020747  101517.6328  101517.6406  ...  3.870000e-08   
47744  4.462517  0.010743  102259.7891  102259.7891  ...  7.730000e-09   
47750 -1.991696  0.017999  100848.6094  100848.6094  ...  7.100000e-10   
47754  1.184948  0.019498  100899.0000  100899.0000  ...  2.430000e-07   
47759 -1.986166  0.017553  101374.0859  101374.0859  ...  2.270000e-08   

               TS      TREFHT       Z1000         Z200       ZBOT  year  \
0      295.622253  293.301514  197.698624  12234.78809  64.372635  2003   
1      302.496826  302.654083   71.571518  12463.97266  66.834389  2007   
2      299.854919  293.339996  160.414246  12099.36133  64.209663  2002   
3      301.606934  299.973450   72.840614  12379.26855  66.243294  2000   
4      295.819488  295.101257  218.449570  12261.22656  64.876427  2000   
...           ...         ...         ...          ...        ...   ...   
47743  302.773254  302.241974  134.770569  12433.16016  66.823296  2001   
47744  295.015991  293.339417  192.308746  12169.76367  64.421112  2008   
47750  302.839966  301.316742   75.255516  12388.10938  66.508980  1997   
47754  302.068481  300.820374   79.624161  12387.60742  66.427940  2004   
47759  301.325226  300.146851  121.040375  12352.48535  66.221062  2008   

       month  date  LABELS  
0          8     4       0  
1         10     6       1  
2          3    31       0  
3          9     6       0  
4          9     6       0  
...      ...   ...     ...  
47743      8     4       0  
47744     10     3       0  
47750      6    18       0  
47754     10     3       0  
47759     10    12       0  

[25763 rows x 22 columns]

In [17]:
# Drop all feature duplicates, which may have different labels that confuse our model
df_temp2 = df_temp1.drop_duplicates(subset=df_temp1.columns[0:-1], keep=False)

In [18]:
df_temp2_labels = df_temp2[["LABELS"]]
df_temp2_labels

LABELS
0           0
2           0
3           0
5           2
6           0
...       ...
47742       0
47743       0
47744       0
47750       0
47759       0

[19447 rows x 1 columns]

In [19]:
df_temp2 = df_temp2.drop(columns=["LABELS"])
df_temp2

lat       lon        TMQ       U850       V850      UBOT  \
0     -24.758801  242.1875  16.019615  -4.391696   4.777769 -6.388222   
2      23.820078  276.8750  11.556691  -2.483993  -6.009627 -3.503036   
3      13.494133  253.1250  53.186630   0.150933  -1.319407  3.757741   
5     -24.524120  241.5625  43.424503  10.390884 -10.737404  2.822728   
6     -24.993481  242.1875  34.667477  -1.841543   3.988539  1.742689   
...          ...       ...        ...        ...        ...       ...   
47742  23.585398  277.5000  24.418753   3.641168   6.957775 -8.155352   
47743  23.585398  276.5625  41.815079  -5.981042   7.609122 -8.963073   
47744 -24.993481  242.5000  23.160349  -6.694213   1.401017 -8.668851   
47750  13.494133  253.7500  44.489532  -2.837747  -1.062834 -3.629961   
47759  24.054759  276.8750  49.550251  -2.582931  -0.844238 -6.318487   

            VBOT    QREFHT           PS          PSL  ...        T500  \
0       7.725320  0.010277  102326.2344  102326.2344  ...  261.823212   
2      -5.921963  0.007468  101885.3906  101885.3906  ...  259.610718   
3      -2.172120  0.018809  100824.6328  100824.6328  ...  267.374329   
5     -11.261213  0.014424  101099.9375  101099.9375  ...  264.098419   
6       6.661032  0.013957  101552.2656  101552.2656  ...  264.075195   
...          ...       ...          ...          ...  ...         ...   
47742   3.388716  0.013139  102010.6250  102012.7266  ...  261.399536   
47743   2.837600  0.020747  101517.6328  101517.6406  ...  265.900665   
47744   4.462517  0.010743  102259.7891  102259.7891  ...  262.539703   
47750  -1.991696  0.017999  100848.6094  100848.6094  ...  268.018402   
47759  -1.986166  0.017553  101374.0859  101374.0859  ...  265.335571   

              PRECT          TS      TREFHT       Z1000         Z200  \
0      6.660000e-09  295.622253  293.301514  197.698624  12234.78809   
2      0.000000e+00  299.854919  293.339996  160.414246  12099.36133   
3      9.800000e-08  301.606934  299.973450   72.840614  12379.26855   
5      5.650000e-08  296.483215  296.177185   95.622093  12237.61719   
6      3.570000e-09  299.140747  297.297180  134.934036  12242.46875   
...             ...         ...         ...         ...          ...   
47742  8.420000e-19  297.565277  295.948151  173.441727  12256.40039   
47743  3.870000e-08  302.773254  302.241974  134.770569  12433.16016   
47744  7.730000e-09  295.015991  293.339417  192.308746  12169.76367   
47750  7.100000e-10  302.839966  301.316742   75.255516  12388.10938   
47759  2.270000e-08  301.325226  300.146851  121.040375  12352.48535   

            ZBOT  year  month  date  
0      64.372635  2003      8     4  
2      64.209663  2002      3    31  
3      66.243294  2000      9     6  
5      65.247345  2001      9    19  
6      65.431206  2001      4    25  
...          ...   ...    ...   ...  
47742  65.099129  2001      2     2  
47743  66.823296  2001      8     4  
47744  64.421112  2008     10     3  
47750  66.508980  1997      6    18  
47759  66.221062  2008     10    12  

[19447 rows x 21 columns]

In [20]:
df_temp2_std = (df_temp2-df_temp2.mean())/df_temp2.std()
df_temp2_np_std = df_temp2_std.to_numpy()
df_temp2_labels_np = df_temp2_labels.to_numpy()

In [21]:
#train a model to make predictions on conflicting values
#https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html

rf_clf_for_good_data = RandomForestClassifier(n_estimators = 100, max_features = 'sqrt', max_depth = None, 
                                              criterion = 'entropy', class_weight = None).fit(df_temp2_np_std, df_temp2_labels_np.ravel())


In [22]:
# predicting on duplicates
# duplicates is a mask
duplicates = df_temp1.duplicated(subset=df_temp1.columns[0:-1], keep='first')
duplicates_df = df_temp1[duplicates]
duplicates_df_std = (duplicates_df-duplicates_df.mean())/duplicates_df.std()
duplicates_df_std = duplicates_df_std.drop(columns=["LABELS"])
duplicates_df_std_np = duplicates_df_std.to_numpy()

predictions = rf_clf_for_good_data.predict(duplicates_df_std_np)

In [23]:
labels_new = pd.DataFrame(data=predictions, columns=["LABELS"])

In [24]:
labels_new

LABELS
0          0
1          0
2          0
3          0
4          0
...      ...
3198       0
3199       0
3200       0
3201       0
3202       0

[3203 rows x 1 columns]

In [25]:
duplicates_df = duplicates_df.reset_index()
duplicates_df = duplicates_df.drop(columns=["index","LABELS"])
duplicates_df

lat       lon        TMQ       U850       V850       UBOT  \
0    -24.289439  241.2500  34.993114  -1.250208   1.830655  -1.164386   
1     23.820078  276.8750  47.643150  -8.193987  -0.793653   2.222956   
2    -31.095176  353.4375  17.494404   5.393440 -10.987731   2.693818   
3     21.473272  275.3125  47.726372  -7.007339   9.557825  -7.793356   
4    -24.758801  242.5000  16.059599   3.491873   2.355471   0.478088   
...         ...       ...        ...        ...        ...        ...   
3198 -20.769231  229.6875  17.247395   5.472986  -3.642907  -1.382102   
3199  13.494133  252.8125  53.929550  -7.672997  -4.186466   5.395471   
3200 -21.003911  229.6875  34.676754  -9.601542   1.853052 -11.285004   
3201 -21.003911  229.0625  23.064512  -3.096328  -3.706821  -3.422838   
3202  13.024772  253.4375  53.848255  10.059551  -0.746791   9.813080   

           VBOT    QREFHT           PS          PSL  ...        T500  \
0      0.791331  0.013837  102127.5781  102127.5781  ...  264.752441   
1     -2.483554  0.014301  101641.0391  101641.0391  ...  267.657288   
2    -11.873419  0.007240  102210.5703  102210.5703  ...  257.774780   
3     -0.364407  0.016162  101481.4141  101481.4609  ...  267.678680   
4      3.135037  0.007984  101822.5000  101822.5000  ...  259.952759   
...         ...       ...          ...          ...  ...         ...   
3198  -4.805233  0.012555  101502.6406  101502.6406  ...  265.733765   
3199   5.290195  0.018129  100943.5156  100943.5156  ...  266.613464   
3200   4.884233  0.013464  102099.4609  102099.4609  ...  264.383758   
3201  -1.319323  0.013747  101791.6016  101791.6016  ...  266.522919   
3202   1.184948  0.019498  100899.0000  100899.0000  ...  266.822144   

             PRECT          TS      TREFHT       Z1000         Z200  \
0     3.730000e-15  299.001129  297.850922  184.584137  12322.55469   
1     1.640000e-13  302.688385  301.619019  144.736191  12478.61816   
2     4.920000e-09  290.675598  289.177429  185.113617  12021.61426   
3     3.050000e-11  302.522949  301.916351  131.041611  12470.16699   
4     6.140000e-12  296.630707  293.299530  155.424042  12095.59961   
...            ...         ...         ...         ...          ...   
3198  5.370000e-17  297.768890  296.710236  130.367966  12308.53027   
3199  4.480000e-20  302.127685  298.890289   82.900589  12407.66797   
3200  1.590000e-07  297.313141  296.051178  180.867950  12299.45996   
3201  4.100000e-15  296.893219  296.203308  154.993484  12338.62500   
3202  2.430000e-07  302.068481  300.820374   79.624161  12387.60742   

           ZBOT  year  month  date  
0     65.601128  2001      5     7  
1     66.431099  2010      7     5  
2     63.365555  2002      8    24  
3     66.546646  2010      7     5  
4     64.323791  2006      6    22  
...         ...   ...    ...   ...  
3198  65.280739  2000      9    28  
3199  65.909958  2009      7    15  
3200  65.126869  2010     10    19  
3201  65.235397  1996     10     3  
3202  66.427940  2004     10     3  

[3203 rows x 21 columns]

In [26]:
final_df1 = pd.concat([duplicates_df, labels_new], axis = 1)
final_df1

lat       lon        TMQ       U850       V850       UBOT  \
0    -24.289439  241.2500  34.993114  -1.250208   1.830655  -1.164386   
1     23.820078  276.8750  47.643150  -8.193987  -0.793653   2.222956   
2    -31.095176  353.4375  17.494404   5.393440 -10.987731   2.693818   
3     21.473272  275.3125  47.726372  -7.007339   9.557825  -7.793356   
4    -24.758801  242.5000  16.059599   3.491873   2.355471   0.478088   
...         ...       ...        ...        ...        ...        ...   
3198 -20.769231  229.6875  17.247395   5.472986  -3.642907  -1.382102   
3199  13.494133  252.8125  53.929550  -7.672997  -4.186466   5.395471   
3200 -21.003911  229.6875  34.676754  -9.601542   1.853052 -11.285004   
3201 -21.003911  229.0625  23.064512  -3.096328  -3.706821  -3.422838   
3202  13.024772  253.4375  53.848255  10.059551  -0.746791   9.813080   

           VBOT    QREFHT           PS          PSL  ...         PRECT  \
0      0.791331  0.013837  102127.5781  102127.5781  ...  3.730000e-15   
1     -2.483554  0.014301  101641.0391  101641.0391  ...  1.640000e-13   
2    -11.873419  0.007240  102210.5703  102210.5703  ...  4.920000e-09   
3     -0.364407  0.016162  101481.4141  101481.4609  ...  3.050000e-11   
4      3.135037  0.007984  101822.5000  101822.5000  ...  6.140000e-12   
...         ...       ...          ...          ...  ...           ...   
3198  -4.805233  0.012555  101502.6406  101502.6406  ...  5.370000e-17   
3199   5.290195  0.018129  100943.5156  100943.5156  ...  4.480000e-20   
3200   4.884233  0.013464  102099.4609  102099.4609  ...  1.590000e-07   
3201  -1.319323  0.013747  101791.6016  101791.6016  ...  4.100000e-15   
3202   1.184948  0.019498  100899.0000  100899.0000  ...  2.430000e-07   

              TS      TREFHT       Z1000         Z200       ZBOT  year  month  \
0     299.001129  297.850922  184.584137  12322.55469  65.601128  2001      5   
1     302.688385  301.619019  144.736191  12478.61816  66.431099  2010      7   
2     290.675598  289.177429  185.113617  12021.61426  63.365555  2002      8   
3     302.522949  301.916351  131.041611  12470.16699  66.546646  2010      7   
4     296.630707  293.299530  155.424042  12095.59961  64.323791  2006      6   
...          ...         ...         ...          ...        ...   ...    ...   
3198  297.768890  296.710236  130.367966  12308.53027  65.280739  2000      9   
3199  302.127685  298.890289   82.900589  12407.66797  65.909958  2009      7   
3200  297.313141  296.051178  180.867950  12299.45996  65.126869  2010     10   
3201  296.893219  296.203308  154.993484  12338.62500  65.235397  1996     10   
3202  302.068481  300.820374   79.624161  12387.60742  66.427940  2004     10   

      date  LABELS  
0        7       0  
1        5       0  
2       24       0  
3        5       0  
4       22       0  
...    ...     ...  
3198    28       0  
3199    15       0  
3200    19       0  
3201     3       0  
3202     3       0  

[3203 rows x 22 columns]

In [27]:
df_temp2 = pd.concat([df_temp2, df_temp2_labels], axis = 1)
df_temp2

lat       lon        TMQ       U850       V850      UBOT  \
0     -24.758801  242.1875  16.019615  -4.391696   4.777769 -6.388222   
2      23.820078  276.8750  11.556691  -2.483993  -6.009627 -3.503036   
3      13.494133  253.1250  53.186630   0.150933  -1.319407  3.757741   
5     -24.524120  241.5625  43.424503  10.390884 -10.737404  2.822728   
6     -24.993481  242.1875  34.667477  -1.841543   3.988539  1.742689   
...          ...       ...        ...        ...        ...       ...   
47742  23.585398  277.5000  24.418753   3.641168   6.957775 -8.155352   
47743  23.585398  276.5625  41.815079  -5.981042   7.609122 -8.963073   
47744 -24.993481  242.5000  23.160349  -6.694213   1.401017 -8.668851   
47750  13.494133  253.7500  44.489532  -2.837747  -1.062834 -3.629961   
47759  24.054759  276.8750  49.550251  -2.582931  -0.844238 -6.318487   

            VBOT    QREFHT           PS          PSL  ...         PRECT  \
0       7.725320  0.010277  102326.2344  102326.2344  ...  6.660000e-09   
2      -5.921963  0.007468  101885.3906  101885.3906  ...  0.000000e+00   
3      -2.172120  0.018809  100824.6328  100824.6328  ...  9.800000e-08   
5     -11.261213  0.014424  101099.9375  101099.9375  ...  5.650000e-08   
6       6.661032  0.013957  101552.2656  101552.2656  ...  3.570000e-09   
...          ...       ...          ...          ...  ...           ...   
47742   3.388716  0.013139  102010.6250  102012.7266  ...  8.420000e-19   
47743   2.837600  0.020747  101517.6328  101517.6406  ...  3.870000e-08   
47744   4.462517  0.010743  102259.7891  102259.7891  ...  7.730000e-09   
47750  -1.991696  0.017999  100848.6094  100848.6094  ...  7.100000e-10   
47759  -1.986166  0.017553  101374.0859  101374.0859  ...  2.270000e-08   

               TS      TREFHT       Z1000         Z200       ZBOT  year  \
0      295.622253  293.301514  197.698624  12234.78809  64.372635  2003   
2      299.854919  293.339996  160.414246  12099.36133  64.209663  2002   
3      301.606934  299.973450   72.840614  12379.26855  66.243294  2000   
5      296.483215  296.177185   95.622093  12237.61719  65.247345  2001   
6      299.140747  297.297180  134.934036  12242.46875  65.431206  2001   
...           ...         ...         ...          ...        ...   ...   
47742  297.565277  295.948151  173.441727  12256.40039  65.099129  2001   
47743  302.773254  302.241974  134.770569  12433.16016  66.823296  2001   
47744  295.015991  293.339417  192.308746  12169.76367  64.421112  2008   
47750  302.839966  301.316742   75.255516  12388.10938  66.508980  1997   
47759  301.325226  300.146851  121.040375  12352.48535  66.221062  2008   

       month  date  LABELS  
0          8     4       0  
2          3    31       0  
3          9     6       0  
5          9    19       2  
6          4    25       0  
...      ...   ...     ...  
47742      2     2       0  
47743      8     4       0  
47744     10     3       0  
47750      6    18       0  
47759     10    12       0  

[19447 rows x 22 columns]

In [28]:
final_df = pd.concat([df_temp2, final_df1], ignore_index = True)

In [29]:
final_df

lat       lon        TMQ       U850       V850       UBOT  \
0     -24.758801  242.1875  16.019615  -4.391696   4.777769  -6.388222   
1      23.820078  276.8750  11.556691  -2.483993  -6.009627  -3.503036   
2      13.494133  253.1250  53.186630   0.150933  -1.319407   3.757741   
3     -24.524120  241.5625  43.424503  10.390884 -10.737404   2.822728   
4     -24.993481  242.1875  34.667477  -1.841543   3.988539   1.742689   
...          ...       ...        ...        ...        ...        ...   
22645 -20.769231  229.6875  17.247395   5.472986  -3.642907  -1.382102   
22646  13.494133  252.8125  53.929550  -7.672997  -4.186466   5.395471   
22647 -21.003911  229.6875  34.676754  -9.601542   1.853052 -11.285004   
22648 -21.003911  229.0625  23.064512  -3.096328  -3.706821  -3.422838   
22649  13.024772  253.4375  53.848255  10.059551  -0.746791   9.813080   

            VBOT    QREFHT           PS          PSL  ...         PRECT  \
0       7.725320  0.010277  102326.2344  102326.2344  ...  6.660000e-09   
1      -5.921963  0.007468  101885.3906  101885.3906  ...  0.000000e+00   
2      -2.172120  0.018809  100824.6328  100824.6328  ...  9.800000e-08   
3     -11.261213  0.014424  101099.9375  101099.9375  ...  5.650000e-08   
4       6.661032  0.013957  101552.2656  101552.2656  ...  3.570000e-09   
...          ...       ...          ...          ...  ...           ...   
22645  -4.805233  0.012555  101502.6406  101502.6406  ...  5.370000e-17   
22646   5.290195  0.018129  100943.5156  100943.5156  ...  4.480000e-20   
22647   4.884233  0.013464  102099.4609  102099.4609  ...  1.590000e-07   
22648  -1.319323  0.013747  101791.6016  101791.6016  ...  4.100000e-15   
22649   1.184948  0.019498  100899.0000  100899.0000  ...  2.430000e-07   

               TS      TREFHT       Z1000         Z200       ZBOT  year  \
0      295.622253  293.301514  197.698624  12234.78809  64.372635  2003   
1      299.854919  293.339996  160.414246  12099.36133  64.209663  2002   
2      301.606934  299.973450   72.840614  12379.26855  66.243294  2000   
3      296.483215  296.177185   95.622093  12237.61719  65.247345  2001   
4      299.140747  297.297180  134.934036  12242.46875  65.431206  2001   
...           ...         ...         ...          ...        ...   ...   
22645  297.768890  296.710236  130.367966  12308.53027  65.280739  2000   
22646  302.127685  298.890289   82.900589  12407.66797  65.909958  2009   
22647  297.313141  296.051178  180.867950  12299.45996  65.126869  2010   
22648  296.893219  296.203308  154.993484  12338.62500  65.235397  1996   
22649  302.068481  300.820374   79.624161  12387.60742  66.427940  2004   

       month  date  LABELS  
0          8     4       0  
1          3    31       0  
2          9     6       0  
3          9    19       2  
4          4    25       0  
...      ...   ...     ...  
22645      9    28       0  
22646      7    15       0  
22647     10    19       0  
22648     10     3       0  
22649     10     3       0  

[22650 rows x 22 columns]

In [30]:
final_df.to_csv("final_df_after_removing_all_dups_WITHOUT_lat_long_WITHOUT_smote.csv")

In [31]:
df_train = final_df

In [32]:
df_train

lat       lon        TMQ       U850       V850       UBOT  \
0     -24.758801  242.1875  16.019615  -4.391696   4.777769  -6.388222   
1      23.820078  276.8750  11.556691  -2.483993  -6.009627  -3.503036   
2      13.494133  253.1250  53.186630   0.150933  -1.319407   3.757741   
3     -24.524120  241.5625  43.424503  10.390884 -10.737404   2.822728   
4     -24.993481  242.1875  34.667477  -1.841543   3.988539   1.742689   
...          ...       ...        ...        ...        ...        ...   
22645 -20.769231  229.6875  17.247395   5.472986  -3.642907  -1.382102   
22646  13.494133  252.8125  53.929550  -7.672997  -4.186466   5.395471   
22647 -21.003911  229.6875  34.676754  -9.601542   1.853052 -11.285004   
22648 -21.003911  229.0625  23.064512  -3.096328  -3.706821  -3.422838   
22649  13.024772  253.4375  53.848255  10.059551  -0.746791   9.813080   

            VBOT    QREFHT           PS          PSL  ...         PRECT  \
0       7.725320  0.010277  102326.2344  102326.2344  ...  6.660000e-09   
1      -5.921963  0.007468  101885.3906  101885.3906  ...  0.000000e+00   
2      -2.172120  0.018809  100824.6328  100824.6328  ...  9.800000e-08   
3     -11.261213  0.014424  101099.9375  101099.9375  ...  5.650000e-08   
4       6.661032  0.013957  101552.2656  101552.2656  ...  3.570000e-09   
...          ...       ...          ...          ...  ...           ...   
22645  -4.805233  0.012555  101502.6406  101502.6406  ...  5.370000e-17   
22646   5.290195  0.018129  100943.5156  100943.5156  ...  4.480000e-20   
22647   4.884233  0.013464  102099.4609  102099.4609  ...  1.590000e-07   
22648  -1.319323  0.013747  101791.6016  101791.6016  ...  4.100000e-15   
22649   1.184948  0.019498  100899.0000  100899.0000  ...  2.430000e-07   

               TS      TREFHT       Z1000         Z200       ZBOT  year  \
0      295.622253  293.301514  197.698624  12234.78809  64.372635  2003   
1      299.854919  293.339996  160.414246  12099.36133  64.209663  2002   
2      301.606934  299.973450   72.840614  12379.26855  66.243294  2000   
3      296.483215  296.177185   95.622093  12237.61719  65.247345  2001   
4      299.140747  297.297180  134.934036  12242.46875  65.431206  2001   
...           ...         ...         ...          ...        ...   ...   
22645  297.768890  296.710236  130.367966  12308.53027  65.280739  2000   
22646  302.127685  298.890289   82.900589  12407.66797  65.909958  2009   
22647  297.313141  296.051178  180.867950  12299.45996  65.126869  2010   
22648  296.893219  296.203308  154.993484  12338.62500  65.235397  1996   
22649  302.068481  300.820374   79.624161  12387.60742  66.427940  2004   

       month  date  LABELS  
0          8     4       0  
1          3    31       0  
2          9     6       0  
3          9    19       2  
4          4    25       0  
...      ...   ...     ...  
22645      9    28       0  
22646      7    15       0  
22647     10    19       0  
22648     10     3       0  
22649     10     3       0  

[22650 rows x 22 columns]

In [33]:
latest_labels = df_train[["LABELS"]]

In [38]:
#https://datascience.stackexchange.com/questions/13567/ways-to-deal-with-longitude-latitude-feature
#https://heartbeat.comet.ml/working-with-geospatial-data-in-machine-learning-ad4097c7228d
#https://stackoverflow.com/questions/14059094/i-want-to-multiply-two-columns-in-a-pandas-dataframe-and-add-the-result-into-a-n
df_train['cos_lat'] = np.cos(df_train[['lat']])
df_train['cos_long'] = np.cos(df_train[['lon']])
df_train['sin_lat'] = np.sin(df_train[['lat']])
df_train['sin_long'] = np.sin(df_train[['lon']])

df_train['x'] = df_train['cos_lat'] * df_train['cos_long']
df_train['y'] = df_train['cos_lat'] * df_train['sin_long']
df_train['z'] = df_train['sin_lat']

#df_train = df_train.drop(columns=['cos_lat','cos_long','sin_lat','sin_long', 'lat', 'lon'])
df_train = df_train.drop(columns=['cos_lat','cos_long','sin_lat','sin_long'])


# df_train["x"] = np.cos(df_train[['lat']]) * np.cos(df_train[['lon']])
# df_train["y"] = np.cos(df_train[['lat']]) * np.sin(df_train[['lon']])
# df_train["z"] = np.sin(df_train[['lat']])

In [39]:
# df_train["rad_lat"] = np.radians(df_train[['lat']])
# df_train["rad_lon"] = np.radians(df_train[['lon']])

In [40]:
df_train.nunique()

lat          24
lon          35
TMQ       22540
U850      22555
V850      22558
UBOT      22556
VBOT      22555
QREFHT    22533
PS        21520
PSL       21537
T200      22068
T500      21789
PRECT      6506
TS         9827
TREFHT    21892
Z1000     22535
Z200      21880
ZBOT      21964
year         15
month        12
date         31
LABELS        3
x           120
y           120
z            24
dtype: int64

In [41]:
#Trying clustering:
from sklearn.cluster import KMeans ,AgglomerativeClustering

# creates 5 clusters using hierarchical clustering.
agc = AgglomerativeClustering(n_clusters = 5, affinity='euclidean', linkage='ward')
df_train['cluster_lat'] = agc.fit_predict(df_train[['lat']])


In [42]:
agc = AgglomerativeClustering(n_clusters = 7, affinity='euclidean', linkage='ward')
df_train['cluster_lon'] = agc.fit_predict(df_train[['lon']])

In [43]:
#https://stackabuse.com/one-hot-encoding-in-python-with-pandas-and-scikit-learn/
#z = pd.get_dummies(df_train.cluster_lon, prefix='Long')
#z.head()

In [44]:
#df_train = pd.concat([df_train, y, z], axis=1)

In [45]:
#df_train

In [46]:
df_train.columns

Index(['lat', 'lon', 'TMQ', 'U850', 'V850', 'UBOT', 'VBOT', 'QREFHT', 'PS',
       'PSL', 'T200', 'T500', 'PRECT', 'TS', 'TREFHT', 'Z1000', 'Z200', 'ZBOT',
       'year', 'month', 'date', 'LABELS', 'x', 'y', 'z', 'cluster_lat',
       'cluster_lon'],
      dtype='object')

In [47]:
#df_train = df_train.drop(columns=['Lat_0', 'Lat_1', 'Lat_2', 'Lat_3', 'Lat_4', 'Long_0', 'Long_1', 'Long_2', 'Long_3', 'Long_4', 'Long_5', 'Long_6'])

In [48]:
df_train = df_train.drop(columns=["LABELS"])
df_train = pd.concat([df_train, latest_labels],axis=1)


In [49]:
df_train

lat       lon        TMQ       U850       V850       UBOT  \
0     -24.758801  242.1875  16.019615  -4.391696   4.777769  -6.388222   
1      23.820078  276.8750  11.556691  -2.483993  -6.009627  -3.503036   
2      13.494133  253.1250  53.186630   0.150933  -1.319407   3.757741   
3     -24.524120  241.5625  43.424503  10.390884 -10.737404   2.822728   
4     -24.993481  242.1875  34.667477  -1.841543   3.988539   1.742689   
...          ...       ...        ...        ...        ...        ...   
22645 -20.769231  229.6875  17.247395   5.472986  -3.642907  -1.382102   
22646  13.494133  252.8125  53.929550  -7.672997  -4.186466   5.395471   
22647 -21.003911  229.6875  34.676754  -9.601542   1.853052 -11.285004   
22648 -21.003911  229.0625  23.064512  -3.096328  -3.706821  -3.422838   
22649  13.024772  253.4375  53.848255  10.059551  -0.746791   9.813080   

            VBOT    QREFHT           PS          PSL  ...       ZBOT  year  \
0       7.725320  0.010277  102326.2344  102326.2344  ...  64.372635  2003   
1      -5.921963  0.007468  101885.3906  101885.3906  ...  64.209663  2002   
2      -2.172120  0.018809  100824.6328  100824.6328  ...  66.243294  2000   
3     -11.261213  0.014424  101099.9375  101099.9375  ...  65.247345  2001   
4       6.661032  0.013957  101552.2656  101552.2656  ...  65.431206  2001   
...          ...       ...          ...          ...  ...        ...   ...   
22645  -4.805233  0.012555  101502.6406  101502.6406  ...  65.280739  2000   
22646   5.290195  0.018129  100943.5156  100943.5156  ...  65.909958  2009   
22647   4.884233  0.013464  102099.4609  102099.4609  ...  65.126869  2010   
22648  -1.319323  0.013747  101791.6016  101791.6016  ...  65.235397  1996   
22649   1.184948  0.019498  100899.0000  100899.0000  ...  66.427940  2004   

       month  date         x         y         z  cluster_lat  cluster_lon  \
0          8     4 -0.893379 -0.261608  0.365287            4            2   
1          3    31  0.233623  0.102889 -0.966868            0            6   
2          9     6 -0.134827  0.584272  0.800280            2            4   
3          9    19 -0.773434  0.273709  0.571737            4            2   
4          4    25 -0.950409 -0.278308  0.138810            4            2   
...      ...   ...       ...       ...       ...          ...          ...   
22645      9    28  0.320974  0.117615 -0.939757            3            3   
22646      7    15  0.051330  0.597425  0.800280            2            4   
22647     10    19  0.517358  0.189576 -0.834507            3            3   
22648     10     3  0.530478 -0.148966 -0.834507            3            3   
22649     10     3 -0.460512  0.769486  0.442515            2            4   

       LABELS  
0           0  
1           0  
2           0  
3           2  
4           0  
...       ...  
22645       0  
22646       0  
22647       0  
22648       0  
22649       0  

[22650 rows x 27 columns]

In [123]:
df_train.to_csv("final_df_after_removing_all_dups_WITH_lat_long_WITHOUT_smote.csv")

In [50]:
df_train

lat       lon        TMQ       U850       V850       UBOT  \
0     -24.758801  242.1875  16.019615  -4.391696   4.777769  -6.388222   
1      23.820078  276.8750  11.556691  -2.483993  -6.009627  -3.503036   
2      13.494133  253.1250  53.186630   0.150933  -1.319407   3.757741   
3     -24.524120  241.5625  43.424503  10.390884 -10.737404   2.822728   
4     -24.993481  242.1875  34.667477  -1.841543   3.988539   1.742689   
...          ...       ...        ...        ...        ...        ...   
22645 -20.769231  229.6875  17.247395   5.472986  -3.642907  -1.382102   
22646  13.494133  252.8125  53.929550  -7.672997  -4.186466   5.395471   
22647 -21.003911  229.6875  34.676754  -9.601542   1.853052 -11.285004   
22648 -21.003911  229.0625  23.064512  -3.096328  -3.706821  -3.422838   
22649  13.024772  253.4375  53.848255  10.059551  -0.746791   9.813080   

            VBOT    QREFHT           PS          PSL  ...       ZBOT  year  \
0       7.725320  0.010277  102326.2344  102326.2344  ...  64.372635  2003   
1      -5.921963  0.007468  101885.3906  101885.3906  ...  64.209663  2002   
2      -2.172120  0.018809  100824.6328  100824.6328  ...  66.243294  2000   
3     -11.261213  0.014424  101099.9375  101099.9375  ...  65.247345  2001   
4       6.661032  0.013957  101552.2656  101552.2656  ...  65.431206  2001   
...          ...       ...          ...          ...  ...        ...   ...   
22645  -4.805233  0.012555  101502.6406  101502.6406  ...  65.280739  2000   
22646   5.290195  0.018129  100943.5156  100943.5156  ...  65.909958  2009   
22647   4.884233  0.013464  102099.4609  102099.4609  ...  65.126869  2010   
22648  -1.319323  0.013747  101791.6016  101791.6016  ...  65.235397  1996   
22649   1.184948  0.019498  100899.0000  100899.0000  ...  66.427940  2004   

       month  date         x         y         z  cluster_lat  cluster_lon  \
0          8     4 -0.893379 -0.261608  0.365287            4            2   
1          3    31  0.233623  0.102889 -0.966868            0            6   
2          9     6 -0.134827  0.584272  0.800280            2            4   
3          9    19 -0.773434  0.273709  0.571737            4            2   
4          4    25 -0.950409 -0.278308  0.138810            4            2   
...      ...   ...       ...       ...       ...          ...          ...   
22645      9    28  0.320974  0.117615 -0.939757            3            3   
22646      7    15  0.051330  0.597425  0.800280            2            4   
22647     10    19  0.517358  0.189576 -0.834507            3            3   
22648     10     3  0.530478 -0.148966 -0.834507            3            3   
22649     10     3 -0.460512  0.769486  0.442515            2            4   

       LABELS  
0           0  
1           0  
2           0  
3           2  
4           0  
...       ...  
22645       0  
22646       0  
22647       0  
22648       0  
22649       0  

[22650 rows x 27 columns]

In [51]:
def df_to_train_test_split(df):
    #df is the normalized or standardized df
    #labels are just the labels.
#         So we need 6760 test exmaples, in 18:4:1 ratio roughly to match the train test.<br>
#         So we need:<br>
#         1s - 294<br>
#         2s - 1176<br>
#         0s - 5290<br>
    data_with_labels = df
    data_with_labels_0s = data_with_labels[data_with_labels["LABELS"] == 0]
    data_with_labels_1s = data_with_labels[data_with_labels["LABELS"] == 1]
    data_with_labels_2s = data_with_labels[data_with_labels["LABELS"] == 2]

    data_1_test = data_with_labels_1s.iloc[0:109]
    data_2_test = data_with_labels_2s.iloc[0:458]
    data_0_test = data_with_labels_0s.iloc[0:2827]

    data_1_train = data_with_labels_1s.iloc[109:]
    data_2_train = data_with_labels_2s.iloc[458:]
    data_0_train = data_with_labels_0s.iloc[2827:]

    test = pd.concat([data_1_test, data_2_test, data_0_test])
    #Houston, we have a problem, we need to shuffle the indices, but pandas has us covered
    #https://stackoverflow.com/questions/29576430/shuffle-dataframe-rows
    train = pd.concat([data_1_train, data_2_train, data_0_train])

    #Shuffling:
    #df = df.sample(frac=1).reset_index(drop=True)
    test = test.sample(frac=1).reset_index(drop=True)
    train = train.sample(frac=1).reset_index(drop=True)

    #Finally, we have our train and test sets.
    #Let's try to follow this post: https://github.com/rahulrrai/multinomial-logistic-regression/blob/master/multinomial-logistic-regression.ipynb
    train_np = train.to_numpy()
    test_np = test.to_numpy()

    #number of training examples
    #this is 41000 in our case
    num_of_train = train_np.shape[0]
    num_of_test = test_np.shape[0]
    #retaining just the features
    X_train = train_np[:,:-1]
    X_test = test_np[:,:-1]
    ##As we are using vector implementation adding a column in X with all the value 1
    # I'm guessing this is the bias term added to our train matrix itself
#     X_train = np.hstack((np.ones((num_of_train,1)),X_train))
#     X_test = np.hstack((np.ones((num_of_test,1)), X_test))
    #output 
    y_train = train_np[:,-1:]
    y_test = test_np[:,-1:]
    #each individual entry in y is a numpy array, let's see if this works out.
    
    return X_train, X_test, y_train, y_test

In [52]:
# df_train = (df_train-df_train.mean())/df_train.std()

In [53]:
X_train, X_test, y_train, y_test = df_to_train_test_split(df_train)

In [56]:
X_train_std = standardizer_new(X_train)
X_train_std

array([[-0.75678168, -0.94636599,  0.16091109, ..., -1.44576836,
         0.8869663 ,  0.06516717],
       [ 1.1901006 ,  0.1737116 ,  0.9296968 , ..., -1.27974786,
        -1.12632523, -1.52864192],
       [-0.76702843, -0.95393409, -0.39941444, ..., -1.36646413,
         0.8869663 ,  0.06516717],
       ...,
       [ 0.69825665, -0.40903147,  1.01005923, ...,  0.34805923,
         0.21586913,  0.59643687],
       [-1.21788538,  2.03546221, -1.92117202, ...,  0.48594517,
        -0.45522805, -0.99737222],
       [ 1.17985385,  0.19641588,  0.22157071, ..., -1.40648021,
        -1.12632523,  1.65897626]])

In [131]:
np.savetxt("X_train_std.csv", X_train_std, delimiter=",")
np.savetxt("y_train.csv", y_train, delimiter=",")

In [57]:
y_train = y_train.astype(int)
y_test = y_test.astype(int)

In [58]:
y_train.ravel().shape

(19256,)

# Sampling:

### SMOTE:

In [46]:
from imblearn.over_sampling import SMOTE
from collections import Counter
#https://www.analyticsvidhya.com/blog/2020/10/overcoming-class-imbalance-using-smote-techniques/

In [47]:
y_train = y_train.astype(int)
y_test = y_test.astype(int)

In [48]:
np.unique(y_train, return_counts=True)

(array([0, 1, 2]), array([16044,   612,  2600], dtype=int64))

# Use these to train 1:

In [49]:
smt = SMOTE()
X_train_sm, y_train_sm = smt.fit_resample(X_train, y_train)

In [50]:
np.unique(y_train_sm, return_counts=True)

(array([0, 1, 2]), array([16044, 16044, 16044], dtype=int64))

In [59]:
from imblearn.over_sampling import ADASYN

In [60]:
np.unique(y_train, return_counts=True)

(array([0, 1, 2]), array([16038,   621,  2597], dtype=int64))

# Use these to train 2:

In [61]:
ada = ADASYN(random_state = 130)
X_train_ada, y_train_ada = ada.fit_resample(X_train, y_train)

In [62]:
np.unique(y_train_ada, return_counts=True)

(array([0, 1, 2]), array([16038, 16054, 15852], dtype=int64))

In [134]:
from imblearn.combine import SMOTETomek

In [135]:
np.unique(y_train, return_counts=True)

(array([0, 1, 2]), array([16059,   613,  2584], dtype=int64))

# Use these to train 3:

In [57]:
smtom = SMOTETomek(random_state=139)
X_train_smotm, y_train_smotm = smtom.fit_resample(X_train, y_train)

In [58]:
np.unique(y_train_smotm, return_counts=True)

(array([0, 1, 2]), array([16022, 16044, 16022], dtype=int64))

In [59]:
from imblearn.combine import SMOTEENN

In [60]:
np.unique(y_train, return_counts=True)

(array([0, 1, 2]), array([16044,   612,  2600], dtype=int64))

# Use these to train 4:

In [61]:
smenn = SMOTEENN()
X_train_smenn, y_train_smenn = smenn.fit_resample(X_train, y_train)

In [62]:
np.unique(y_train_smenn, return_counts=True)

(array([0, 1, 2]), array([15355, 16023, 15871], dtype=int64))

# Normalized and Standardized datasets:

In [72]:
#82.7514% without x,y,z lat long handling
#with handling and replacement = 81.908%
# with handling and without replacement = 82.899%

#adding radians to the above without replacement of anything at all = 82.899%
#adding radians did nothing so we won't retain it

#trying with label encoded lat long clusters, retaining x,y,z and lat long = 83.07%

#trial with one hot lat long clusters dropping label encoded ones = 83.10% - it's not much of a gain

In [478]:
pd.DataFrame(X_train)

0         1          2         3         4         5         6   \
0     -21.238592  229.6875  17.884888  3.284857  1.008598  0.920735  1.260540   
1      22.177314  244.3750  17.295719  1.021269  2.767562 -2.015126 -4.720677   
2     -31.095176  354.3750  16.500547  9.212470 -5.704645  7.525238 -3.084753   
3     -21.238592  229.3750  32.180393  3.692166  3.130262  0.458399 -2.034898   
4      12.790091  252.5000  49.634556 -8.007788  0.696787 -4.313917 -1.955434   
...          ...       ...        ...       ...       ...       ...       ...   
19251 -24.758801  242.5000  25.846441 -6.581431 -2.622495 -9.362361 -2.060400   
19252 -24.993481  241.8750  33.089977  1.654827 -2.795381 -3.421939  1.798562   
19253  12.790091  253.7500  28.784447 -5.876598 -3.851452 -3.811282 -2.661985   
19254 -30.391134  354.0625  29.879532  5.223663  1.996673  4.368197 -0.689402   
19255  21.473272  275.0000  47.460720 -7.697452 -0.412080 -6.215268 -0.290380   

             7            8            9   ...           16         17  \
0      0.009134  101497.1406  101497.1406  ...  12250.85645  64.689049   
1      0.009383  101570.1953  101570.1953  ...  12301.57422  63.778980   
2      0.007865  101782.6172  101782.6172  ...  12103.76953  63.407429   
3      0.014717  101594.7266  101594.7266  ...  12335.21191  65.561752   
4      0.019288  100955.7109  100955.7109  ...  12356.34180  66.384529   
...         ...          ...          ...  ...          ...        ...   
19251  0.011347  102544.7188  102544.7188  ...  12142.51855  64.753441   
19252  0.012624  101764.0625  101764.0625  ...  12302.27637  64.712753   
19253  0.016750  101215.4063  101215.4063  ...  12387.76855  66.014320   
19254  0.010657  102250.1250  102250.1250  ...  12176.99219  63.749729   
19255  0.019853  101042.1016  101042.1016  ...  12385.65039  66.691994   

           18    19    20        21        22        23   24   25  
0      2009.0   7.0  27.0  0.685379  0.251144 -0.683507  3.0  3.0  
1      2002.0   3.0  31.0 -0.770750  0.609660 -0.185092  0.0  5.0  
2      2000.0   9.0  23.0 -0.769620  0.555234  0.315279  1.0  1.0  
3      2002.0   8.0  30.0  0.729396  0.028268 -0.683507  3.0  3.0  
4      2009.0   6.0   2.0  0.378104  0.898786  0.221859  2.0  4.0  
...       ...   ...   ...       ...       ...       ...  ...  ...  
19251  2007.0  10.0   6.0 -0.769683 -0.523597  0.365287  4.0  2.0  
19252  2000.0   9.0  28.0 -0.989941  0.027363  0.138810  4.0  2.0  
19253  2001.0   3.0  24.0 -0.733709  0.642222  0.221859  2.0  4.0  
19254  2010.0   8.0  30.0 -0.307323  0.418570  0.854606  1.0  1.0  
19255  1999.0   9.0   3.0 -0.095938  0.863560  0.495036  0.0  0.0  

[19256 rows x 26 columns]

In [55]:
def standardizer_new(X_train):
    df = pd.DataFrame(X_train)
    #df = df.drop(columns=[0])
    df = (df-df.mean())/df.std()
    X_train = df.to_numpy()
    #num_of_train = X_train.shape[0]
    #X_train = np.hstack((np.ones((num_of_train,1)),X_train))
    return X_train

In [63]:
X_train_sm_std = standardizer_new(X_train_sm)
X_train_sm_std

array([[ 1.        , -0.97312069, -0.67772802, ..., -1.2241902 ,
        -1.01667351, -0.7576788 ],
       [ 1.        ,  0.65425598, -0.38140242, ...,  0.98419382,
        -0.51646704,  1.13608891],
       [ 1.        , -1.24091685,  2.05758528, ..., -1.71494221,
         0.48394589, -1.76026171],
       ...,
       [ 1.        , -1.26125897,  2.07240142, ..., -1.4450198 ,
        -0.97914456, -1.64607766],
       [ 1.        , -0.98342054, -0.66195105, ...,  0.24806581,
        -1.01667351,  0.80189461],
       [ 1.        , -0.9937204 , -0.66814115, ...,  0.24806581,
        -1.01667351,  0.80189461]])

In [64]:
X_train_ada_std = standardizer_new(X_train_ada)
X_train_ada_std

array([[ 1.        , -1.008293  , -0.61749265, ..., -1.15520445,
        -1.00557076, -0.73795449],
       [ 1.        ,  0.63749805, -0.30675372, ...,  1.08403845,
        -0.49031094,  1.16161912],
       [ 1.        , -1.27911938,  2.25086668, ..., -1.65281398,
         0.54020871, -1.74361111],
       ...,
       [ 1.        , -1.0395422 , -0.60515588, ..., -1.15520445,
         1.05546854,  1.27335875],
       [ 1.        , -1.0395422 , -0.60620312, ..., -1.15520445,
         1.05546854,  1.27335875],
       [ 1.        , -1.0395422 , -0.6077415 , ..., -1.15520445,
         1.05546854,  1.27335875]])

In [65]:
X_train_smotm_std = standardizer_new(X_train_smotm)
X_train_smotm_std

array([[ 1.        , -0.97274252, -0.68325424, ..., -1.23184886,
        -1.0197742 , -0.75728239],
       [ 1.        ,  0.65204439, -0.38720168, ...,  0.98171188,
        -0.51945374,  1.13613197],
       [ 1.        , -1.24011251,  2.04953867, ..., -1.72375125,
         0.48118717, -1.75967822],
       ...,
       [ 1.        ,  1.11985043,  0.19717733, ..., -1.47780006,
        -1.0197742 , -1.64830091],
       [ 1.        , -1.0035929 , -0.68310281, ..., -1.47780006,
        -0.51945374, -0.8686597 ],
       [ 1.        , -1.25737641,  2.05197691, ..., -0.35636081,
        -0.57909268, -0.30366338]])

In [66]:
X_train_smenn_std = standardizer_new(X_train_smenn)
X_train_smenn_std

array([[ 1.        , -0.98157164, -0.68069532, ..., -1.222777  ,
        -1.01528852, -0.75549955],
       [ 1.        ,  0.64413197, -0.38353326, ...,  0.97932125,
        -0.51520121,  1.14159035],
       [ 1.        , -1.24909249,  2.06233907, ..., -1.71213217,
         0.48497341, -1.75984127],
       ...,
       [ 1.        , -0.99695084, -0.66734087, ..., -1.222777  ,
        -1.01528852,  1.14159035],
       [ 1.        , -1.26518413,  2.05901638, ..., -0.48874425,
         0.98506071,  1.3647774 ],
       [ 1.        , -1.011949  , -0.6513067 , ...,  0.48996608,
        -1.01528852,  0.80680978]])

In [67]:
X_train_sm_std.shape

(48132, 22)

In [68]:
X_test_std = standardizer_new(X_test)
X_test_std.shape

(3394, 22)

# SMOTE:

In [69]:
#https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html
logreg_smote_clf = LogisticRegression(solver='saga', max_iter = 10000, class_weight = None, C= 1.5).fit(X_train_sm_std,y_train_sm.ravel())
logreg_smote_predictions = logreg_smote_clf.predict(X_test_std)
logreg_smote_accuracy = logreg_smote_clf.score(X_test_std, y_test.ravel())
print(logreg_smote_accuracy)

0.47878609310548026


In [70]:
np.unique(logreg_smote_predictions)

array([0, 1, 2])

# ADA:

In [71]:
#https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html
logreg_ada_clf = LogisticRegression(solver='saga', max_iter = 10000, class_weight = None, C= 1.5).fit(X_train_ada_std,y_train_ada.ravel())
logreg_ada_predictions = logreg_ada_clf.predict(X_test_std)
logreg_ada_accuracy = logreg_ada_clf.score(X_test_std, y_test.ravel())
print(logreg_ada_accuracy)

0.5088391278727166


In [72]:
np.unique(logreg_ada_predictions)

array([0, 1, 2])

In [140]:
np.savetxt("X_train_ada_std.csv", X_train_ada_std, delimiter=",")
np.savetxt("y_train_ada.csv", y_train_ada, delimiter=",")
np.savetxt("X_test_std.csv", X_test_std, delimiter=",")
np.savetxt("y_test.csv", y_test, delimiter=",")

# SMOTE Tomek:

In [74]:
#https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html
logreg_smotm_clf = LogisticRegression(solver='saga', max_iter = 10000, class_weight = None, C= 1.5).fit(X_train_smotm_std,y_train_smotm.ravel())
logreg_smotm_predictions = logreg_smotm_clf.predict(X_test_std)
logreg_smotm_accuracy = logreg_smotm_clf.score(X_test_std, y_test.ravel())
print(logreg_smotm_accuracy)

0.47967000589275194


In [75]:
np.unique(logreg_smotm_predictions)

array([0, 1, 2])

# Smote ENN:

In [76]:
#https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html
logreg_smenn_clf = LogisticRegression(solver='saga', max_iter = 10000, class_weight = None, C= 1.5).fit(X_train_smenn_std,y_train_smenn.ravel())
logreg_smenn_predictions = logreg_smenn_clf.predict(X_test_std)
logreg_smenn_accuracy = logreg_smenn_clf.score(X_test_std, y_test.ravel())
print(logreg_smenn_accuracy)

0.4664113140836771


In [77]:
np.unique(logreg_smenn_predictions)

array([0, 1, 2])

In [78]:
np.savetxt("X_train_smenn_std.csv", X_train_smenn_std, delimiter=",")
np.savetxt("y_train_smenn.csv", y_train_smenn, delimiter=",")
np.savetxt("X_test_std.csv", X_test_std, delimiter=",")
np.savetxt("y_test.csv", y_test, delimiter=",")

In [164]:
# X_train_sm, y_train_sm = smt.fit_resample(X_train, y_train)
# X_train_ada, y_train_ada = ada.fit_resample(X_train, y_train)
# X_train_smotm, y_train_smotm = smtom.fit_resample(X_train, y_train)
# X_train_smenn, y_train_smenn = smenn.fit_resample(X_train, y_train)

In [143]:
X_train_std

array([[ 1.        ,  1.10812661, -0.59823377, ...,  1.54338133,
        -0.25935858,  1.21059296],
       [ 1.        , -0.78752193, -0.95393409, ...,  1.05309245,
         0.57586323,  1.42593772],
       [ 1.        ,  1.07738636,  0.14343924, ..., -0.17262976,
        -1.51219131,  0.9952482 ],
       ...,
       [ 1.        , -0.95146991, -0.67391469, ...,  1.05309245,
        -0.67696949, -0.61983751],
       [ 1.        , -0.93097641, -0.65121041, ..., -0.66291864,
        -2.34741312,  0.34921392],
       [ 1.        ,  1.08763311,  0.13587115, ...,  1.29823689,
        -0.25935858,  1.42593772]])